services:
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - application
    restart: unless-stopped
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - rails-mysql-data:/var/lib/mysql
    networks:
      - application
      - storage
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
  rails-app:
    build: .
    image: rails-rails-web-app
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - app-storage:/app/storage
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql-db
      REDIS_URL: ${REDIS_URL}
    command: bash -c "bundle exec rails server -b 0.0.0.0"
    # command: >
    #   bash -c "
    #     apt-get update &&
    #     apt-get install -y nfs-common &&
    #     mkdir -p /mnt/shared &&
    #     mount -t nfs 172.28.0.10:/exports /mnt/shared &&
    #     bundle exec rails server -b 0.0.0.0
    #   "
    networks:
      - application
      - storage
      - monitoring 
  migrator:
    build: .
    image: rails-rails-migrator
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql-db
      REDIS_URL: ${REDIS_URL}
    command: bash -c "bundle exec rails db:prepare"
    networks:
      - application
  nginx:
    image: nginx:latest
    container_name: rails-nginx
    ports:
      - "80:80"
    depends_on:
      - rails-app
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - public
      - application
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
  # nfs-server:
  #   image: erichough/nfs-server:latest
  #   container_name: nfs-server
  #   privileged: true
  #   environment:
  #     NFS_EXPORT_0: "/exports *(rw,sync,no_subtree_check,no_root_squash)"
  #   volumes:
  #     - ~/iris-sys-recs-2026/exports:/exports
  #   networks:
  #     storage:
  #       ipv4_address: 172.28.0.10
  

volumes:
  rails-mysql-data:
  app-storage:
  grafana_data:
  # nfs_data:
  
networks:
  public:
  application:
  storage:
    # driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.28.0.0/16
  monitoring: