services:
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - application
    restart: unless-stopped
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - rails-mysql-data:/var/lib/mysql
    networks:
      - application
      - storage
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
  rails-app:
    build: .
    image: rails-rails-web-app
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - app-storage:/app/storage
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql-db
      REDIS_URL: ${REDIS_URL}
    command: bash -c "bundle exec rails server -b 0.0.0.0"
    networks:
      - application
      - storage
      - monitoring 
  migrator:
    build: .
    image: rails-rails-migrator
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql-db
      REDIS_URL: ${REDIS_URL}
    command: bash -c "bundle exec rails db:prepare"
    networks:
      - application
  nginx:
    image: nginx:latest
    container_name: rails-nginx
    ports:
      - "80:80"
    depends_on:
      - rails-app
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - public
      - application
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring
      - application
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - monitoring
      - application
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - monitoring
      - application
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring
      - application
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - --nginx.scrape-uri=http://rails-nginx/nginx_status
    depends_on:
      - nginx
    networks:
      - monitoring
      - application

volumes:
  rails-mysql-data:
  app-storage:
  grafana_data:

networks:
  public:
  application:
  storage:
  monitoring: